### ISSUE TITLE
There will be changes and improvements for the indexes page moviepy

### ISSUE THREAD

**Issue by Doctor2023** [devlocalhost/moviepy#2]
I was just wondering if they are going to make any improvements to the indexes project moviepy

**Comment by devlocalhost** [comment]
I think you're a little bit confused. Let me explain what moviepy is:

Moviepy is a python script which scrapes https://edytjedhgmdhm.abfhaqrhbnf.workers.dev and https://odd-bird-1319.zwuhygoaqe.workers.dev

I created this, because the website can be painful to use sometimes, because there are many folders, which will slow the browser and loading times. The script I made saves your time, by looking for exactly what you want. It is not instant, but it is faster

**Comment by Doctor2023** [comment]
> I think you're a little bit confused. Let me explain what moviepy is:
> 
> Moviepy is a python script which scrapes https://edytjedhgmdhm.abfhaqrhbnf.workers.dev and https://odd-bird-1319.zwuhygoaqe.workers.dev
> 
> I created this, because the website can be painful to use sometimes, because there are many folders, which will slow the browser and loading times. The script I made saves your time, by looking for exactly what you want. It is not instant, but it is faster

Ok friend thanks you
